# fly.toml file generated for single-file-gpt on 2023-04-19T13:44:29-05:00

app = "single-file-gpt"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ord"
processes = []

[env]
  PORT = "4000"


[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 2500
    soft_limit = 2000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
